version: '3.8'

services:
  go-mission-app:
    build:
      context: .
      dockerfile: Dockerfile
      target: production
    ports:
      - "9639:3000"
    environment:
      - NODE_ENV=production
      - NITRO_HOST=0.0.0.0
      - NITRO_PORT=3000
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost:3000/"]
      timeout: 10s
      retries: 3
      start_period: 30s
      interval: 30s
    networks:
      - go-mission-network

networks:
  go-mission-network:
    driver: bridge 